### ISSUE TITLE
Criar propriedade para especificação de idioma

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/stories#5]
Criar a propriedade `language` e seus respectivos métodos de definição e obtenção.

Lembrar adicionar nas classes de *storage* um método para filtragem através do idioma.

**Comment by maikenegreiros** [comment]
Essa propriedade será tipada como string @johnnysaymon ? Será criado algum enum?

**Comment by johnnysaymon** [comment]
Será do tipo `string` @maikenegreiros
