### ISSUE TITLE
Adicionar propriedade com referências de Idiomas

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/stories#6]
Adicionar a propriedade `languageReferences` que irá conter um `array` onde a chave será a sigla do idioma e o valor o id da *Story* referenciada. Exemplo:

```php
$languageReferences = [
    'pt-BR'  => 1,
    'en' => 2,
    'es' => 3
];
```

O código para representação do idioma deve ser compatível a norma ISO 639-1 (https://pt.wikipedia.org/wiki/ISO_639)

### Objetivo

Tornar possível a vinculação entre *Storys* que tem o mesmo conteúdo mas só diferem no idioma.

### Alterações

Além de adicionar a propriedade na classe *Story*e os métodos de definição de obtenção dos dados, é necessário refletir os valores nos *storages*

**Comment by maikenegreiros** [comment]
@johnnysaymon eu não entendi bem como isso irá funcionar. Esse valor inteiro será o id da story?

**Comment by johnnysaymon** [comment]
Isso @maikenegreiros .

Uma `Story` no idioma português pode ter uma tradução em inglês. Nesse caso ambas irão se referenciar. Exemplo:

```php
$storyPtBr = new Story('Título de Exemplo', Status::ACTIVE);
$storyPtBr->setId(1);

$storyEn = new Story('Example Title', Status::ACTIVE);
$storyEn->setId(2);

$storyPtBr->setLanguageReferences(['en' => $storyEn->getId()]);
$storyEn->setLanguageReferences(['pt-BR' => $storyPtBr->getId()]);

$storage->store($storyPtBr)->store($storyEn);

```

**Comment by maikenegreiros** [comment]
E no BD @johnnysaymon ? Como será feita essa associação?

**Comment by johnnysaymon** [comment]
Você pode armazenar como um campo JSON @maikenegreiros
